# Generated by Django 3.1 on 2023-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230326_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
