# Generated by Django 3.1 on 2023-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230419_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(max_length=100, null=True),
        ),
    ]
